#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

while IFS=":" read -r username _ userid _ homedir _
do
    echo "$username:$userid:$homedir"
done < "/etc/passwd"
