#!/usr/bin/env bash
# bad good bad
count=1
while [ $count -lt 21 ]
do
    case $count in
        5)
            echo "bad luck from China"
			echo "5"
            ;;
        10)
            echo "bad luck from Japan"
			echo "10"
            ;;
		18)
		   echo "bad luck from Italy"
		   echo "18"
		   ;;
		   
        *)
            echo "$count"
            ;;
    esac
    ((count++))
done
