#!/bin/bash
# Add firewall rules

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
# add forward rule1s
sudo sysctl -w net.ipv4.ip_forward=1
sudo ufw allow 8080/tcp
sudo ufw route allow proto tcp from any to any port 8080 port 80
